lib/PayPal/Api/Sale.php, lib/PayPal/Api/TransactionFee.php, tests/PayPal/Test/Api/SaleTest.php, tests/PayPal/Test/Api/TransactionFeeTest.php
I am raising this PR mostly for discussion while I wait for PayPal support engineers to respond.
Last week we discovered that a new "transaction_fee" element had been added to the response for a POST request to /v1/payments/payment. This causes an issue with this SDK as reflection is used to map the JSON to PHP Objects.
Problem JSON
```json
{
"id": "PAY-2DD06538S7025641FKTHAEII",
"create_time": "2015-02-01T02:38:26.026Z",
"update_time": "2015-02-01T02:38:26.026Z",
"state": "approved",
"intent": "sale",
"payer": {
"payment_method": "paypal",
"payer_info": {
"email": "chaitanya@**********",
"first_name": "Chaitanya",
"last_name": "Kuber",
"payer_id": "6RT3WYKUX89LN"
}
},
"transactions": [
{
"amount": {
"total": "5.00",
"currency": "AUD",
"details": {}
},
"description": "BTQ Order", …
```
=> added transaction fee support to sale class

.travis.yml, lib/PayPal/Validation/JsonValidator.php
* Made behavior compatible fix for PHP 7 (so JsonValidator behaves the same for PHP 5.x and PHP 7.x) for empty string/null values. PHP 7.x will report an error on json_decode if the string is empty or null.
* Add Travis-CI PHP 7.0 support.
=> Add Travis-CI PHP 7.0 support

sample/index.php
Fixing a typo "Uncliamed" -> "Unclaimed" in sample docs.
=> Fixed unclaimed typo.

lib/PayPal/Api/FuturePayment.php, lib/PayPal/Common/PayPalResourceModel.php, sample/index.php, sample/invoice/CreateThirdPartyInvoice.php, sample/lipp/ObtainUserConsent.php
- Enables Third Party Invoicing
- Included Sample
- Related Issue: https://github.com/paypal/PayPal-PHP-SDK/issues/99
=> Enabled Third Party Invoicing

lib/PayPal/Core/PayPalCredentialManager.php
Looks like this should be `ClientSecret`?
=> Duplicate conditional expression in PayPalCredentialManager.php

composer.json
psr/log is now at 1.0.1 but held back to 1.0.0.
as per https://getcomposer.org/doc/articles/versions.md#caret
Many thanks.
=> Allow updates of psr/log package <2.0.0

lib/PayPal/Core/PayPalHttpConnection.php
@jaypatel512 
- PHP 5.6:
- PayPal-PHP-SDK 1.7.4:
- Debug ID(s):
file /lib/PayPal/Core\PayPalHttpConnection.php line 150 reads
// Get Request and Response Headers
$requestHeaders = curl_getinfo($ch, CURLINFO_HEADER_OUT);
//Using alternative solution to CURLINFO_HEADER_SIZE as it throws invalid number when called using PROXY.
$responseHeaderSize = strlen($result) - curl_getinfo($ch, CURLINFO_SIZE_DOWNLOAD);
$responseHeaders = substr($result, 0, $responseHeaderSize);
$result = substr($result, $responseHeaderSize);
The response getting from curl_exec is a string, which is binary. In my case strlen is treating this binary string as UTF8 and is returning a different strlen than the string is when written to disk, using characters like 'äöü ... '. strlen seems to be replaced with mb_strlen, …
=> bugfix: UTF8 encoding in result response from sandbox, corrupts json response

lib/PayPal/Core/PayPalHttpConnection.php
Passing null as length will not make mb_substr use it's default, instead it will interpret it as 0.
$result = mb_substr($result, $responseHeaderSize, null, '8bit');
Instead use:
$result = mb_substr($result, $responseHeaderSize, mb_strlen($result), '8bit');
=> Error: Could not generate new Access token. Invalid response from server 

lib/PayPal/Api/FundingInstrument.php, sample/billing/CreateBillingAgreementWithCreditCard.php, sample/doc/billing/CreateBillingAgreementWithCreditCard.html, sample/doc/payments/AuthorizePayment.html, sample/doc/payments/CreatePayment.html, sample/payments/AuthorizePayment.php, sample/payments/CreatePayment.php
- Fixed deprecation messages.
- Fixes #639.
- Fixes #648.
- Updated Samples.
=> Use PaymentCard instead of CreditCard

lib/PayPal/Core/PayPalHttpConnection.php, lib/PayPal/Handler/RestHandler.php, lib/PayPal/Rest/ApiContext.php, tests/PayPal/Test/Rest/ApiContextTest.php
In order to allow better re-usage of ApiContext, do not automatically set the PayPal-Request-ID and allow manual setting of the PayPal-Request-ID value.
Also remove the automatic retries, so that the developer has full control on retry conditions.
=> PayPal Request ID changes

lib/PayPal/Common/PayPalResourceModel.php
=> Don't iterate if object is null

lib/PayPal/Api/VerifyWebhookSignature.php, sample/notifications/ValidateWebhookEvent.php, tests/PayPal/Test/Api/VerifyWebhookSignatureTest.php
- Fixes #798
Add a new `setRequestBody` which takes the raw webhook notification request body and re-uses the exact request body to do verification.
=> Add request body for VerifyWebhookSignature

README.md
It annoyed me having to copy the url's so I have fixed a few extra spaces in the README.md causing GitHub to not render the links. I also switched the HTTP url's to use HTTPS where possible such as for php.net.
=> Fixed markdown links and made them HTTPS

lib/PayPal/Core/PayPalConfigManager.php
PHP 7.1, CentOS; when attempting to get the link for the oauth button to obtain login scopes, our dev server triggered an E_WARNING:
```sh
Whoops\Exception\ErrorException thrown with message "strstr(): Empty needle"
Stacktrace:
#12 Whoops\Exception\ErrorException in /httpdocs/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalConfigManager.php:103
#11 strstr in /httpdocs/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalConfigManager.php:103
#10 PayPal\Core\PayPalConfigManager:get in /httpdocs/vendor/paypal/rest-api-sdk-php/lib/PayPal/Rest/ApiContext.php:143
#9 PayPal\Rest\ApiContext:get in /httpdocs/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/OpenIdSession.php:31
```
This error was negated by checking for an empty string in 482c153, with 8af4d7d being the corresponding indentation …
=> E_WARNING strstr(): Empty needle

lib/PayPal/Core/PayPalHttpConfig.php
With openssl 1.1 using only `TLSv1` in the cipher list causes the following exception which is fixed by adding TLSv1.2 to the list:
Exception PayPal\Exception\PayPalConnectionException: "PayPal\Exception\PayPalConnectionException: error:141640B5:SSL routines:tls_construct_client_hello:no ciphers available"
=> Add TLSv1.2 to cipher list

lib/PayPal/Core/PayPalHttpConnection.php
- Removes complex conditions around parsing response headers
I also suggest that the logging should use the context array instead of forcing the execution of calculating the debug strings, but that should be in a future PR.
=> Avoids calculating header size in curl responses

lib/PayPal/Auth/OAuthTokenCredential.php, lib/PayPal/Transport/PayPalRestCall.php
Proxy setting were not being respected, so once  is
returned, setHttpProxy() is called to add the proxy option if
need prior to getting and OAuth token or executing a call to
PayPal
=> Make Proxy Configuration Work

lib/PayPal/Converter/FormatConverter.php, tests/PayPal/Test/Common/FormatConverterTest.php
=> Add HUF as non-decimal currency

README.md
update readme for direct credit card restriction
=> update readme for direct credit card restriction

sample/bootstrap.php
I added line which helps to add custome cache directory instead of using prebuilt $CACHE_PATH
=> Custom cache directory line was not written

lib/PayPal/Api/CartBase.php, lib/PayPal/Api/ItemList.php, tests/PayPal/Test/Api/ItemListTest.php
SDK/Library version: 1.13.0
Environment: Sandbox
PayPal-Debug-ID values: 3a5fd0a7adf56
I have create an Item array along these lines:
```php
$items = [ null, new Item() ];
$items = array_filter($items, function($value) { return !is_null($value); })
$itemList->setItems($items);
```
Which returns this error from the API:
```json
{"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request" }
```
Here is the generated JSON:
```
{
"intent":"sale",
"payer":{
"payment_method":"paypal"
},
"redirect_urls":{
"return_url":"http://local/?id=67&type=4835&mail_id=8190&success=true",
"cancel_url":"http://local/?id=67&type=4835&mail_id=8190&success=false"
},
"transactions":[
{
"amount":{
"currency":"EUR",
"total":"400"
},
"item_list":{
"items":{
"1":{
"name":"Label", …
```
=> Re-Order the array keys so that JSON will be an array, not an object

tests/PayPal/Test/Api/CreditCardHistoryTest.php, tests/PayPal/Test/Cache/AuthorizationCacheTest.php, tests/PayPal/Test/Common/ModelTest.php, tests/PayPal/Test/Common/PayPalModelTest.php, tests/PayPal/Test/Core/PayPalCredentialManagerTest.php, tests/PayPal/Test/Core/PayPalHttpConfigTest.php, tests/PayPal/Test/Functional/Api/BillingAgreementsFunctionalTest.php, tests/PayPal/Test/Functional/Api/PayoutsFunctionalTest.php, tests/PayPal/Test/Functional/Api/WebhookFunctionalTest.php
I've refactored some tests, using:
- `assertInternalType` instead of `is_*` functions;
- `assertCount` instead of `count` and `sizeof` functions;
- `assertNotSame` instead os strict comparisons `!==`;
- `assertInstanceOf` instead of `instanceof` operator;
- `assertGreaterThan` for mathematical comparisons.
=> Refactoring tests
